### ISSUE TITLE
🤣😂

### ISSUE THREAD

**Issue by Guru322** [DeeCeeXxx/Venom-2#131]
@DGXeon bruh see this shit

**Comment by DGXeon** [comment]
> @DGXeon bruh see this shit

😅😅

**Comment by Guru322** [comment]
> Wow 😳 Amazing issue 😻

Ya💋😂

**Comment by Guru322** [comment]
> > > Wow 😳 Amazing issue 😻
> > 
> > 
> > Ya💋😂
> 
> Do u believe in jesus

Jay shree jesus🙏

**Comment by Guru322** [comment]
Me seeing these kids rip off someone's work
And pretending be pro coders

Nodejs🗣️is not a language😎 it's a js🤓 framework 🗣️

Wow what a enlightening knowledge 😎

**Comment by Guru322** [comment]
> Big fan sir please give me shoutout!
Ask @DeeCeeXxx he is pro coder😎, he wrote this repo alone

**Comment by shizothetechie** [comment]
> Me seeing these kids rip off someone's work And pretending be pro coders
> 
> Nodejs🗣️is not a language😎 it's a js🤓 framework 🗣️
> 
> Wow what an enlightening knowledge 😎

Lol 
i see this kiddos 💀👀
I can't control my self 💀 from laughing 🤣

**Comment by shizothetechie** [comment]
> > Big fan sir please give me shoutout!
> 
> Ask @DeeCeeXxx he is pro coder😎, he wrote this repo alone

Yes yes 
@DeeCeeXxx Sir Please Give him shoutout 🤭😻

**Comment by Guru322** [comment]
> > > Big fan sir please give me shoutout!
> > 
> > 
> > Ask @DeeCeeXxx he is pro coder😎, he wrote this repo alone
> 
> Yes yes @DeeCeeXxx Sir Please Give him shoutout 🤭😻

Ya please 😘

**Comment by Kai0071** [comment]
> > Big fan sir please give me shoutout!
> 
> Ask @DeeCeeXxx he is pro coder😎, he wrote this repo alone

Wow so much wow! 🧐

**Comment by Guru322** [comment]
> > > Big fan sir please give me shoutout!
> > 
> > 
> > Ask @DeeCeeXxx he is pro coder😎, he wrote this repo alone
> 
> Wow so much wow! 🧐

![IMG_20240727_001121](https://github.com/user-attachments/assets/a5855f2e-60da-4156-bdca-29a40143059d)


Irony🤡

**Comment by Guru322** [comment]
Well let them do their shits
We shouldn't get involved with these kids

**Comment by shizothetechie** [comment]
Yes 😂
